### ISSUE TITLE
Replication needed: An error has occurred: [string"?"] 799:attempt to index a nil value

### ISSUE THREAD

**Issue by Kirezar** [Kirezar/VitaGrafixConfigurator#9]
Can someone replicate this error consistently and tell me the cause of it? I tried everything to break the app and can't seem to, always works as intended.

**Comment by Dartegnian** [comment]
Hello, developer! I believe I can pitch in here. I can replicate this issue without fail *every single time* I run the app. I've reinstalled it several times via VitaShell, same thing. Redownloaded it and freshly installed, same.

I upgraded from a really old version of VitaGrafix and, on my first install, my PS Vita's memory slots randomly ejected or something. I had to reboot the console just to get apps working. I don't know why it's been doing that but it's not your program's fault.

I guess that's all I can say. I keep trying to reinstall it, still not working. I've reinstalled VitaGrafix again and the new v4 version of the configurator and it still won't work. I haven't been able to use the v4 version because it always shows me that error.

![2019-01-23-021443](https://user-images.githubusercontent.com/14353938/51556580-8ae9c200-1eb5-11e9-8f4d-911a8fda6f93.png)

**Comment by Kirezar** [comment]
Ok so I suppose i'ts the problem I suspected but that I'm not able to replicate, which is the patchlist.txt not being put into the VitaGrafix folder in ux0:/data, can you confirm that the patchlist.txt file does infact, not exist on that folder for you?

**Comment by Beat-Fusion** [comment]
I had the same problem. Just enter to Vita Shell and delete folder VitaGrafix in ux0:data. Close Vita Shell and start VitaGrafix. This fix the problem for me.

**Comment by Dartegnian** [comment]
Hey, developer. Sorry for the late reply, but it's the weekend and I can have enough free time now. Anyways, as for your concern, I did check the VitaGrafix folder in **ux0:data/VitaGrafix** and it contained files which were normal, to say the least. 

As for **patchlist.txt**, it is totally empty, empty. 0 bytes. Nothing in it all. But it exists inside the folder in the correct location, nonetheless.

**Comment by Kirezar** [comment]
ok, so if you go here [https://github.com/Electry/VitaGrafixPatchlist] and download the patchlist.txt file and put it on your VitaGrafix folder, does it work?

**Comment by Dartegnian** [comment]
Yup, fixes everything. Thanks for the help and thanks for the hard work on the app, too!

**Comment by Kirezar** [comment]
Ok thanks for the help. Basically I won't be able to solve that problem, but I'll implement a safeguard for future instances, so it doesn't crash

**Comment by Doyo69247** [comment]
So i edited the patchlist and config.txt in vitashell to change my cod declassified resolution and fps and it worked but now that every time i open Vitagrafix the same message pops up…what do i do to keep my fixated resolution and also be able to access the vita grafix app without an error popping up.

![Image](https://github.com/user-attachments/assets/5f996477-9ef0-4e51-88bf-0f0f0988f65f)
